chore: rename management ui project and link it to Maven root project

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,6 +4,19 @@ orbs:
   slack: circleci/slack@4.4
   gravitee: gravitee-io/gravitee@1.0
   secrethub: secrethub/cli@1.1
+  gh: circleci/github-cli@1.0
+
+executors:
+  node-lts:
+    parameters:
+      class:
+        description: The resource class
+        type: enum
+        enum: [ 'small', 'medium', 'large', 'xlarge' ]
+        default: 'medium'
+    docker:
+      - image: cimg/node:14.18
+    resource_class: <<parameters.class>>
 
 commands:
   restore-maven-cache:
@@ -47,7 +60,7 @@ jobs:
   build:
     docker:
       - image: cimg/openjdk:11.0
-    resource_class: medium
+    resource_class: xlarge
     steps:
       - checkout
       - attach_workspace:
@@ -238,6 +251,296 @@ jobs:
           command: |
             RELEASE_VERSION=master python ./jenkins-scripts/src/main/python/package_bundles.py
 
+
+  console-webui-install:
+    executor:
+      name: node-lts
+      class: small
+    steps:
+      - checkout
+      - restore_cache:
+          name: Restore NPM cache
+          keys:
+            - gravitee-apim-console-webui-cache-v1-{{ checksum "gravitee-apim-console-webui/package-lock.json" }}
+      - run:
+          name: Install dependencies
+          command: npm install
+          working_directory: gravitee-apim-console-webui
+      - save_cache:
+          name: Save NPM cache
+          key: gravitee-apim-console-webui-cache-v1-{{ checksum "gravitee-apim-console-webui/package-lock.json" }}
+          paths:
+            - ./gravitee-apim-console-webui/node_modules
+      - persist_to_workspace:
+          root: .
+          paths:
+            - gravitee-apim-console-webui/node_modules
+
+  console-webui-lint-test:
+    executor:
+      name: node-lts
+      class: medium
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: Check License
+          command: npm run lint:license
+          working_directory: gravitee-apim-console-webui
+      - run:
+          name: Run Prettier and ESLint
+          command: npm run lint
+          working_directory: gravitee-apim-console-webui
+      - run:
+          name: Run unit tests
+          command: npm run test:ci
+          working_directory: gravitee-apim-console-webui
+      - persist_to_workspace:
+          root: .
+          paths:
+            - gravitee-apim-console-webui/coverage
+      - store_test_results:
+          path: gravitee-apim-console-webui/coverage
+
+  console-webui-sonarcloud-analysis:
+    docker:
+      - image: sonarsource/sonar-scanner-cli
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: Run Sonarcloud Analysis
+          command: sonar-scanner
+          working_directory: gravitee-apim-console-webui
+
+  console-webui-build:
+    executor:
+      name: node-lts
+      class: large
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: Build
+          command: npm run build:prod
+          environment:
+            NODE_OPTIONS: --max_old_space_size=4086
+            BACKEND_ENV: element-zero
+          working_directory: gravitee-apim-console-webui
+      - run:
+          name: Zip dist folder
+          # TODO:
+          #  - Use gzip instead of zip
+          command: zip -r dist.zip dist
+          working_directory: gravitee-apim-console-webui
+      - persist_to_workspace:
+          root: .
+          paths:
+            - gravitee-apim-console-webui/dist
+      - store_artifacts:
+          path: gravitee-apim-console-webui/dist.zip
+          destination: build-output
+
+  console-webui-build-storybook:
+    executor:
+      name: node-lts
+      class: large
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: Build
+          command: npm run build-storybook
+          working_directory: gravitee-apim-console-webui
+          environment:
+            NODE_OPTIONS: --max_old_space_size=3072
+      - persist_to_workspace:
+          root: .
+          paths:
+            - gravitee-apim-console-webui/storybook-static
+
+  console-webui-chromatic-deployment:
+    executor:
+      class: small
+      name: node-lts
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - secrethub/exec:
+          step-name: Running Chromatic
+          # TODO:
+          #  - Handle npx chromatic command failure, make the job fails
+          #  - Create a new project in Chromatic and update the token
+          command: |
+            SB_URL=$(cd gravitee-apim-console-webui && npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-once-uploaded -d=storybook-static | grep -o "View your Storybook at https:\/\/[0-9a-z-]*\.chromatic\.com" | grep -o "https:.*")
+            echo "export SB_URL=$SB_URL" >> $BASH_ENV
+      - gh/setup
+      - run:
+          name: Comment Pull Request
+          command: |
+            # First check there is an associated pull request, otherwise just stop the job here
+            if ! gh pr view --json title;
+            then
+              echo "No PR found for this branch, stopping the job here."
+              exit 0
+            fi
+
+            gh pr comment --body "**Gravitee.io Automatic Deployment**
+
+            📚 View the storybook of this branch [here](${SB_URL})
+            "
+
+
+
+  console-webui-deploy-on-azure-storage:
+    docker:
+      - image: mcr.microsoft.com/azure-cli:latest
+    resource_class: small
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Login into Azure Storage and upload dist
+          # TODO:
+          #  - Update CircleCI env var AZURE_STORAGE_CONNECTION_STRING (one for Console, one for Portal)
+          command: |
+            export BRANCH_ID=$(echo "$CIRCLE_BRANCH" | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr "[:upper:]" "[:lower:]" | cut -c -60)
+            az login --service-principal -u $AZURE_APPLICATION_ID --tenant $AZURE_TENANT -p $AZURE_APPLICATION_SECRET
+            az storage container create -n $BRANCH_ID --public-access blob
+            az storage blob upload-batch -s gravitee-apim-console-webui/dist -d $BRANCH_ID
+
+
+  console-webui-comment-pr-after-deployment:
+    executor:
+      name: node-lts
+      class: small
+    steps:
+      - checkout
+      - gh/setup
+      - run:
+          name: Comment Pull Request
+          command: |
+            # First check there is an associated pull request, otherwise just stop the job here
+            if ! gh pr view --json title;
+            then
+              echo "No PR found for this branch, stopping the job here."
+              exit 0
+            fi
+
+            export BRANCH_ID=$(echo "$CIRCLE_BRANCH" | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr "[:upper:]" "[:lower:]" | cut -c -60)
+            gh pr comment --body "**Gravitee.io Automatic Deployment**
+
+            Congrats, all the CI steps were 🟢 . The Bot was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/${BRANCH_ID}/index.html)! 🚀
+
+            _Notes_: The deployed app is linked to the management API of the Element Zero team's environment."
+
+
+
+  console-webui-publish-images-azure-registry:
+    docker:
+      - image: cimg/openjdk:11.0
+    resource_class: small
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - setup_remote_docker
+      - run:
+          name: Compute Tag for Docker images
+          command: |
+            # Compute tag with branch name, commmit SHA and timestamp. Then slugify it to be sure it can be handled by Docker
+            export TAG=$(echo "${CIRCLE_BRANCH:0:15}-${CIRCLE_SHA1:0:7}" | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)
+            # Workaround for sharing this variable to the next steps
+            echo "export TAG=$TAG" >> $BASH_ENV
+            echo "Docker images will be tagged with: ${TAG}"
+            echo $TAG > docker-tag.txt
+      - run:
+          name: Build & Publish Web UI Docker Image to Azure Registry
+          command: |
+            cp -fr docker/config .
+            cp -fr docker/run.sh .
+
+            export IMAGE_TAG=graviteeio.azurecr.io/apim-console-webui:${TAG}
+            docker build -f docker/Dockerfile-dev -t ${IMAGE_TAG} .
+            echo $AZURE_DOCKER_REGISTRY_PASSWORD | docker login --username $AZURE_DOCKER_REGISTRY_USERNAME --password-stdin graviteeio.azurecr.io
+            docker push ${IMAGE_TAG}
+          working_directory: gravitee-apim-console-webui
+      - persist_to_workspace:
+          root: .
+          paths:
+            - ./docker-tag.txt
+
+  console-webui-deploy-on-azure-cluster:
+    docker:
+      - image: mcr.microsoft.com/azure-cli:latest
+    resource_class: small
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Read tag of Docker images to deploy
+          command: |
+            export TAG=$(cat ./docker-tag.txt)
+            # Workaround for sharing this variable to the next steps
+            echo "export TAG=$TAG" >> $BASH_ENV
+            echo "Will deploy Docker images with tag: ${TAG}"
+      - run:
+          name: Install Helm
+          command: |
+            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
+            helm version
+      - run:
+          name: Install Kubectl
+          command: |
+            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
+            chmod +x ./kubectl
+            mv ./kubectl /usr/local/bin/kubectl
+            kubectl version --client=true
+      - run:
+          name: Helm upgrade and 🚀 to Element Zero cluster
+          command: |
+            az login --service-principal -u $AZURE_APPLICATION_ID --tenant $AZURE_TENANT -p $AZURE_APPLICATION_SECRET
+            az aks get-credentials --resource-group element-zero --name element-zero
+
+            helm upgrade --repo https://helm.gravitee.io \
+                        --install apim \
+                        -n apim \
+                        --reuse-values \
+                        apim3 \
+                        --set "ui.image.repository=graviteeio.azurecr.io/apim-console-webui" \
+                        --set "ui.image.tag=$TAG"
+      - run:
+          name: Helm upgrade and 🚀 to APIM cluster
+          command: |
+            az login --service-principal -u $AZURE_APPLICATION_ID --tenant $AZURE_TENANT -p $AZURE_APPLICATION_SECRET
+            az aks get-credentials --resource-group apim-hprod --name apim-hprod
+
+            helm upgrade --repo https://helm.gravitee.io \
+                        --install apim \
+                        -n apim-master \
+                        --reuse-values \
+                        apim3 \
+                        --set "ui.image.repository=graviteeio.azurecr.io/apim-console-webui" \
+                        --set "ui.image.tag=$TAG"
+
+  purge-master-azure-registry:
+    docker:
+      - image: mcr.microsoft.com/azure-cli:latest
+    resource_class: small
+    steps:
+      - run:
+          name: 🗑 Let's purge all master Apim images older than 1d
+          # TODO:
+          #  - Improve purge of other images and branches
+          command: |
+            az login --service-principal -u $AZURE_APPLICATION_ID --tenant $AZURE_TENANT -p $AZURE_APPLICATION_SECRET
+            az acr run --cmd "acr purge --filter 'apim-console-webui:master-.*' --untagged --ago 1d --keep 3" --registry graviteeio /dev/null
+
 workflows:
   pull_requests:
     when:
@@ -286,7 +589,7 @@ workflows:
               only:
                 - master
                 - /^\d+\.\d+\.x$/
-                - 6170-deploy-on-apim-cluster
+                - merge-master
       - deploy-on-azure-aks:
           context: cicd-orchestrator
           pre-steps:
@@ -306,7 +609,94 @@ workflows:
               only:
                 - master
                 - /^\d+\.\d+\.x$/
-                - 6170-deploy-on-apim-cluster
+                - merge-master
+      - console-webui-install:
+          requires:
+            - pr_secrets_resolution
+      - console-webui-lint-test:
+          requires:
+            - console-webui-install
+      - console-webui-sonarcloud-analysis:
+          context: cicd-orchestrator
+          pre-steps:
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/graviteebot/infra/sonarcloud.io.token
+                var-name: SONAR_TOKEN
+          requires:
+            - console-webui-lint-test
+      - console-webui-build:
+          requires:
+            - console-webui-install
+      - console-webui-build-storybook:
+          requires:
+            - console-webui-install
+      - console-webui-deploy-on-azure-storage:
+          context: cicd-orchestrator
+          pre-steps:
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/application-id
+                var-name: AZURE_APPLICATION_ID
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/tenant
+                var-name: AZURE_TENANT
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/application-secret
+                var-name: AZURE_APPLICATION_SECRET
+          requires:
+            - console-webui-build
+      - console-webui-comment-pr-after-deployment:
+          context: cicd-orchestrator
+          pre-steps:
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/graviteebot/github_personal_access_token
+                var-name: GITHUB_TOKEN
+          requires:
+            - console-webui-deploy-on-azure-storage
+      - console-webui-chromatic-deployment:
+          context: cicd-orchestrator
+          requires:
+            - console-webui-build-storybook
+          pre-steps:
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/graviteebot/github_personal_access_token
+                var-name: GITHUB_TOKEN
+      - console-webui-publish-images-azure-registry:
+          context: cicd-orchestrator
+          pre-steps:
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/docker-registries/graviteeio/username
+                var-name: AZURE_DOCKER_REGISTRY_USERNAME
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/docker-registries/graviteeio/password
+                var-name: AZURE_DOCKER_REGISTRY_PASSWORD
+          requires:
+            - console-webui-build
+          filters:
+            branches:
+              only:
+                - master
+                # To remove after the merge and validation on master
+                - merge-master
+      - console-webui-deploy-on-azure-cluster:
+          context: cicd-orchestrator
+          pre-steps:
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/application-id
+                var-name: AZURE_APPLICATION_ID
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/tenant
+                var-name: AZURE_TENANT
+            - secrethub/env-export:
+                secret-path: graviteeio/cicd/azure/application-secret
+                var-name: AZURE_APPLICATION_SECRET
+          requires:
+            - console-webui-publish-images-azure-registry
+          filters:
+            branches:
+              only:
+                - master
+                # To remove after the merge and validation on master
+                - merge-master
 
   # ---
   # The 2 Workflows Below are there for the CICD Orchestrator to be able to
